/* API-backed effects hydrate protected financial state. */
/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Check, RefreshCw, RotateCcw, WalletCards, X } from "lucide-react-native";
import { useAuth } from "@/components/auth";
import { colors, fontFamilies, radii, spacing } from "@/theme";
import { denyAdminRefund, getAdminFinancialRequests, getAdminTransactions, getRevenueSummary, processAdminRefund, processAdminWithdrawal, rejectAdminWithdrawal, type FinanceRecord, type RefundRequest, type RevenueSummary, type WithdrawalRequest } from "@/services/api";

export function AdminFinanceScreen({mode}:{mode:"transactions"|"requests"|"revenue"}){
  const{session}=useAuth();const token=session?.role==="admin"?session.tokens.accessToken:"";const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[records,setRecords]=useState<FinanceRecord[]>([]);const[withdrawals,setWithdrawals]=useState<WithdrawalRequest[]>([]);const[refunds,setRefunds]=useState<RefundRequest[]>([]);const[revenue,setRevenue]=useState<RevenueSummary|null>(null);
  const load=useCallback(async()=>{if(!token)return;setLoading(true);setError("");try{if(mode==="transactions"){const result=await getAdminTransactions(token);setRecords([...result.bookings,...result.refunds,...result.withdrawals,...result.cancelled].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime()))}else if(mode==="requests"){const result=await getAdminFinancialRequests(token);setWithdrawals(result.withdrawals);setRefunds(result.refunds)}else{const now=new Date();setRevenue(await getRevenueSummary(token,now.getMonth()+1,now.getFullYear()))}}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load financial data.")}finally{setLoading(false)}},[mode,token]);useEffect(()=>{void load()},[load]);
  const action=async(work:()=>Promise<unknown>,message:string)=>{setError("");try{await work();setNotice(message);await load()}catch(caught){setError(caught instanceof Error?caught.message:"Action failed.")}};
  const title=mode==="transactions"?"Transactions":mode==="requests"?"Request Center":"Revenue Summary";
  return <ScrollView contentContainerStyle={s.page}><View style={s.header}><View><Text style={s.eyebrow}>FINANCIAL OPERATIONS</Text><Text style={s.title}>{title}</Text><Text style={s.subtitle}>Razorpay Gateway and RazorpayX-ready operational records.</Text></View><Pressable onPress={()=>void load()} style={s.refresh}><RefreshCw size={15} color={colors.gold}/><Text style={s.refreshText}>Refresh</Text></Pressable></View>{error||notice?<Text style={[s.message,error?s.error:s.success]}>{error||notice}</Text>:null}{loading?<View style={s.loading}><ActivityIndicator color={colors.gold}/></View>:mode==="transactions"?<View style={s.list}>{records.map((item,index)=><Record key={`${item._type}-${item.id}-${index}`} item={item}/>)}</View>:mode==="requests"?<View style={s.columns}><View style={s.panel}><Text style={s.panelTitle}>Withdrawal requests ({withdrawals.length})</Text>{withdrawals.map(item=><View key={item.id} style={s.request}><View style={{flex:1}}><Text style={s.name}>{item.username}</Text><Text style={s.meta}>₹{Number(item.amount).toLocaleString("en-IN")} · {item.upi_id} · {item.beneficiary_name||"Name unavailable"}</Text></View><Action label="Mark paid / Process" Icon={Check} onPress={()=>void action(()=>processAdminWithdrawal(token,item.id),"Withdrawal processed.")}/><Action label="Reject" Icon={X} danger onPress={()=>void action(()=>rejectAdminWithdrawal(token,item.id),"Withdrawal rejected.")}/></View>)}{!withdrawals.length?<Text style={s.empty}>No pending withdrawals.</Text>:null}</View><View style={s.panel}><Text style={s.panelTitle}>Refund requests ({refunds.length})</Text>{refunds.map(item=><View key={item.booking_id} style={s.request}><View style={{flex:1}}><Text style={s.name}>{item.booking_id} · {item.guest_name}</Text><Text style={s.meta}>{item.property_name} · ₹{Number(item.refund_amount||item.advance_amount).toLocaleString("en-IN")}</Text></View><Action label="Refund" Icon={RotateCcw} onPress={()=>void action(()=>processAdminRefund(token,item.booking_id,Number(item.refund_amount||item.advance_amount)),"Refund initiated.")}/><Action label="Deny" Icon={X} danger onPress={()=>void action(()=>denyAdminRefund(token,item.booking_id),"Refund denied.")}/></View>)}{!refunds.length?<Text style={s.empty}>No pending refunds.</Text>:null}</View></View>:<View style={s.metrics}>{revenue?Object.entries(revenue).filter(([,value])=>typeof value==="number").map(([label,value])=><View key={label} style={s.metric}><WalletCards size={18} color={colors.gold}/><Text style={s.metricValue}>₹{Number(value).toLocaleString("en-IN")}</Text><Text style={s.metricLabel}>{label.replace(/([A-Z])/g," $1")}</Text></View>):null}</View>}</ScrollView>
}
function Record({item}:{item:FinanceRecord}){return <View style={s.record}><View style={{flex:1}}><Text style={s.name}>{item.booking_id||item.id} · {item.customer_name||item._type}</Text><Text style={s.meta}>{item.property_name||item.upi_id||"BookStayX"} · {item.payment_method||item._type||"transaction"}</Text></View><View><Text style={s.amount}>₹{Number(item.amount||0).toLocaleString("en-IN")}</Text><Text style={s.status}>{item.refund_status||item.payment_status||item.status}</Text></View></View>}
function Action({label,Icon,onPress,danger}:{label:string;Icon:typeof Check;onPress:()=>void;danger?:boolean}){return <Pressable accessibilityLabel={label} onPress={onPress} style={s.action}><Icon size={15} color={danger?colors.danger:colors.success}/></Pressable>}
const s=StyleSheet.create({page:{padding:spacing.xxl,paddingBottom:80},header:{flexDirection:"row",alignItems:"flex-end",justifyContent:"space-between",gap:16},eyebrow:{color:colors.gold,fontFamily:fontFamilies.sansBold,fontSize:9,letterSpacing:1.5},title:{marginTop:5,color:colors.text,fontFamily:fontFamilies.displaySemiBold,fontSize:32},subtitle:{marginTop:5,color:colors.textMuted,fontFamily:fontFamilies.sans,fontSize:11},refresh:{minHeight:42,flexDirection:"row",alignItems:"center",gap:7,paddingHorizontal:14,borderRadius:10,borderWidth:1,borderColor:colors.hairline},refreshText:{color:colors.gold,fontFamily:fontFamilies.sansSemiBold,fontSize:11},message:{marginTop:16,padding:11,borderRadius:10,fontFamily:fontFamilies.sansMedium,fontSize:11},error:{color:"#FCA5A5",backgroundColor:"rgba(239,68,68,.1)"},success:{color:"#86EFAC",backgroundColor:"rgba(34,197,94,.1)"},loading:{minHeight:260,alignItems:"center",justifyContent:"center"},list:{marginTop:20,gap:8},record:{minHeight:70,flexDirection:"row",alignItems:"center",gap:12,padding:14,borderRadius:12,borderWidth:1,borderColor:colors.hairline,backgroundColor:colors.surface},name:{color:colors.text,fontFamily:fontFamilies.sansSemiBold,fontSize:12},meta:{marginTop:4,color:colors.textMuted,fontFamily:fontFamilies.sans,fontSize:9.5},amount:{textAlign:"right",color:colors.gold,fontFamily:fontFamilies.sansBold,fontSize:13},status:{marginTop:4,textAlign:"right",color:colors.textMuted,fontFamily:fontFamilies.sansMedium,fontSize:8,textTransform:"uppercase"},columns:{marginTop:20,gap:14},panel:{padding:16,borderRadius:radii.largeCard,borderWidth:1,borderColor:colors.hairline,backgroundColor:colors.surface},panelTitle:{color:colors.text,fontFamily:fontFamilies.displaySemiBold,fontSize:20},request:{minHeight:68,flexDirection:"row",alignItems:"center",gap:7,borderBottomWidth:1,borderBottomColor:"rgba(255,255,255,.07)"},action:{width:38,height:38,alignItems:"center",justifyContent:"center",borderRadius:9,backgroundColor:colors.background},empty:{padding:30,textAlign:"center",color:colors.textMuted,fontFamily:fontFamilies.sans,fontSize:10},metrics:{marginTop:20,flexDirection:"row",flexWrap:"wrap",gap:12},metric:{width:"31.5%",minHeight:130,padding:17,borderRadius:radii.largeCard,borderWidth:1,borderColor:colors.hairline,backgroundColor:colors.surface},metricValue:{marginTop:18,color:colors.gold,fontFamily:fontFamilies.sansBold,fontSize:24},metricLabel:{marginTop:6,color:colors.textMuted,fontFamily:fontFamilies.sansMedium,fontSize:9,textTransform:"uppercase"}});
