import { apiRequest } from "./client";

const bearer = (token: string) => ({ Authorization: `Bearer ${token}` });
const query = (params: Record<string, string | number | undefined>) => new URLSearchParams(Object.entries(params).filter((entry): entry is [string, string | number] => entry[1] !== undefined).map(([key, value]) => [key, String(value)])).toString();

export type OwnerUnit = {
  id: number;
  name: string;
  available_persons?: number;
  total_persons?: number;
  amenities?: string[] | string;
  images?: string[] | string;
  price_per_person?: string;
  weekday_price?: string;
  weekend_price?: string;
  special_price?: string;
  special_dates?: unknown[] | string;
  category?: string;
  badge?: string;
  location_label?: string;
  description?: string;
  bedrooms?: number;
  bathrooms?: number;
  bed_config?: string;
  extra_guest_price?: string;
  security_deposit?: string;
  has_food?: boolean;
  meal_plan?: string;
  veg_price?: string;
  non_veg_price?: string;
  kitchen_facility?: string;
  activities?: string[] | string;
  check_in_time?: string;
  check_out_time?: string;
  schedule_note?: string;
  what_you_will_love?: string;
  house_rules?: string;
  cancellation_policy?: string;
  pet_friendly?: boolean;
  smoking_allowed?: boolean;
  total_inventory?: number;
  available_inventory?: number;
  accommodation_type?: string;
};
export type OwnerCalendarDay = {
  date: string;
  status?: string;
  price: string | number | null;
  is_booked?: boolean;
  available_quantity?: number;
  total_capacity?: number;
  booked_quantity?: number;
  booked_seats?: number;
  total_seats?: number;
  available_seats?: number;
  is_soft_locked?: boolean;
  is_payment_initiated?: boolean;
};
export type OwnerLedgerEntry = {
  id: number;
  customer_name: string;
  check_in: string;
  check_out: string;
  payment_mode?: string;
  amount?: number | string;
  advance_amount?: number | string;
  total_amount?: number | string;
  persons?: number;
  note?: string;
  unit_id?: number;
  unit_name?: string;
  source: "website" | "offline";
  booking_id?: string;
  ticket_id?: string | null;
  booking_status?: string;
  guest_phone?: string;
  veg_guest_count?: number | null;
  nonveg_guest_count?: number | null;
  male_guest_count?: number | null;
  female_guest_count?: number | null;
  check_in_time?: string | null;
  check_out_time?: string | null;
  created_at?: string | null;
  items?: Array<{
    unitId: number;
    unitName: string;
    accommodationType?: string;
    persons: number;
    unitQuantity: number;
    subtotal: number;
  }>;
};
export type UnitInput = {
  name: string;
  available_persons: number;
  total_persons: number;
  amenities?: string[];
  images?: string[];
  price_per_person?: string;
  weekday_price?: string;
  weekend_price?: string;
  special_price?: string;
  special_dates?: unknown[];
  category?: string;
  badge?: string;
  location_label?: string;
  description?: string;
  bedrooms?: number;
  bathrooms?: number;
  bed_config?: string;
  extra_guest_price?: string;
  security_deposit?: string;
  meal_plan?: string;
  veg_price?: string;
  non_veg_price?: string;
  kitchen_facility?: string;
  activities?: string[];
  check_in_time?: string;
  check_out_time?: string;
  schedule_note?: string;
  what_you_will_love?: string;
  house_rules?: string;
  cancellation_policy?: string;
  pet_friendly?: boolean;
  smoking_allowed?: boolean;
};
export type OwnerPropertyProfile = { id: string; databaseId: number; slug: string; title: string; category: string; location: string; description: string; checkInTime?: string; checkOutTime?: string; amenities: string[]; activities: string[]; highlights: string[]; policies: string[]; schedule: string[]; images: string[] };
export type OwnerProfile = { id: number; name: string; mobile: string; whatsapp?: string };
export type OwnerDashboard = { owner: OwnerProfile; property: OwnerPropertyProfile; units: OwnerUnit[] };
export type OwnerCalendarResult = { success: true; data: OwnerCalendarDay[] };
export type OfflineLedgerInput = { unit_id: number; customer_name: string; persons: number; check_in: string; check_out: string; payment_mode: "online" | "offline"; amount: number; note?: string };

export const getOwnerProperty = (propertyId: string, token: string) => apiRequest<{ success: true; data: Record<string, unknown> }>(`/api/owners/my-property/${encodeURIComponent(propertyId)}`, { headers: bearer(token) });
export const getOwnerPropertyUnits = (propertyId: string, token: string) => apiRequest<{ success: true; data: OwnerUnit[] }>(`/api/properties/${encodeURIComponent(propertyId)}/units`, { headers: bearer(token) });
export const createOwnerUnit = (propertyId: string, token: string, body: UnitInput) => apiRequest<{ success: true; data: OwnerUnit }>(`/api/properties/${encodeURIComponent(propertyId)}/units`, { method: "POST", headers: bearer(token), body });
export const updateOwnerUnit = (unitId: number, token: string, body: Partial<UnitInput>) => apiRequest<{ success: true; data: OwnerUnit }>(`/api/properties/units/${unitId}`, { method: "PUT", headers: bearer(token), body });
export const deleteOwnerUnit = (unitId: number, token: string) => apiRequest<{ success: true }>(`/api/properties/units/${unitId}`, { method: "DELETE", headers: bearer(token) });
export const getOwnerCalendar = (propertyId: string) => apiRequest<{ success: true; data: OwnerCalendarDay[]; meta: { totalCapacity: number; isVilla: boolean } }>(`/api/properties/${encodeURIComponent(propertyId)}/calendar`);
export const updateOwnerCalendarDay = (propertyId: string, token: string, body: { date: string; price: number; is_booked: boolean }) => apiRequest<{ success: true; message: string }>(`/api/properties/${encodeURIComponent(propertyId)}/calendar`, { method: "PUT", headers: bearer(token), body });
export const getOwnerLedger = (propertyId: string, mobile: string, year: number, month: number, unitId?: number | "all") => apiRequest<{ success: true; data: OwnerLedgerEntry[] }>(`/api/bookings/owner/ledger?${query({ property_id: propertyId, mobile, year, month, unit_id: unitId })}`);
export const getOwnerLedgerUnits = (propertyId: string, mobile: string) => apiRequest<{ success: true; data: { id: number; name: string }[] }>(`/api/bookings/owner/units?${query({ property_id: propertyId, mobile })}`);

export const getProtectedOwnerDashboard = (token: string) => apiRequest<OwnerDashboard & { success: true }>("/api/owners/dashboard", { headers: bearer(token) });
export const createProtectedOwnerUnit = (token: string, body: UnitInput) => apiRequest<{ success: true; data: OwnerUnit }>("/api/owners/dashboard/units", { method: "POST", headers: bearer(token), body });
export const updateProtectedOwnerUnit = (token: string, unitId: number, body: Partial<UnitInput> & Record<string, unknown>) => apiRequest<{ success: true; data: OwnerUnit }>(`/api/owners/dashboard/units/${unitId}`, { method: "PUT", headers: bearer(token), body });
export const deleteProtectedOwnerUnit = (token: string, unitId: number) => apiRequest<{ success: true }>(`/api/owners/dashboard/units/${unitId}`, { method: "DELETE", headers: bearer(token) });
export const getProtectedOwnerCalendar = (token: string, unitId: number, start: string, end: string, excludeBookingId?: string) => apiRequest<OwnerCalendarResult>(`/api/owners/dashboard/calendar?${query({ unitId, start, end, excludeBookingId })}`, { headers: bearer(token) });
export const updateProtectedOwnerRates = (token: string, unitId: number, body: { weekday_price: number; weekend_price: number; special_price?: number; special_dates?: { date: string; price: number }[] }) => apiRequest<{ success: true }>(`/api/owners/dashboard/units/${unitId}/rates`, { method: "PUT", headers: bearer(token), body });
export const updateProtectedOwnerDay = (token: string, unitId: number, date: string, body: { status?: "available" | "booked"; available_quantity?: number; reset_to_default?: boolean; price?: number; force?: boolean; releaseBookings?: boolean }) => apiRequest<{ success: true }>(`/api/owners/dashboard/units/${unitId}/calendar/${date}`, { method: "PUT", headers: bearer(token), body });
export const getProtectedOwnerLedger = (token: string, year: number, month: number, unitId?: number | "all") => apiRequest<{ success: true; data: OwnerLedgerEntry[] }>(`/api/owners/dashboard/ledger?${query({ year, month, unitId })}`, { headers: bearer(token) });
export const createProtectedLedgerEntry = (token: string, body: OfflineLedgerInput) => apiRequest<{ success: true; data: OwnerLedgerEntry }>("/api/owners/dashboard/ledger", { method: "POST", headers: bearer(token), body });
export const updateProtectedLedgerEntry = (token: string, entryId: number, body: Partial<OfflineLedgerInput>) => apiRequest<{ success: true; data: OwnerLedgerEntry }>(`/api/owners/dashboard/ledger/${entryId}`, { method: "PUT", headers: bearer(token), body });
export const deleteProtectedLedgerEntry = (token: string, entryId: number) => apiRequest<{ success: true }>(`/api/owners/dashboard/ledger/${entryId}`, { method: "DELETE", headers: bearer(token) });
export const updateProtectedOwnerProfile = (token: string, body: Record<string, unknown>) => apiRequest<{ success: true }>("/api/owners/dashboard/profile", { method: "PUT", headers: bearer(token), body });
