import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ArrowUpRight, ShieldCheck } from "lucide-react-native";
import { adminSections } from "@/components/admin";
import { colors, fontFamilies, radii, spacing } from "@/theme";

export default function AdminOverview() {
  const operationalModules = adminSections.filter((section) => section.slug !== "overview");
  return <ScrollView contentContainerStyle={styles.page}><View style={styles.heading}><Text style={styles.title}>Administration workspace</Text><Text style={styles.subtitle}>The protected web foundation is ready for the legacy admin workflows.</Text></View><View style={styles.status}><View style={styles.statusIcon}><ShieldCheck size={22} color={colors.success} /></View><View style={styles.statusCopy}><Text style={styles.statusTitle}>Web-only access is active</Text><Text style={styles.statusText}>Admin routes are isolated from Android and iOS while remaining available through Expo Web.</Text></View></View><Text style={styles.sectionTitle}>Implementation map</Text><View style={styles.grid}>{operationalModules.map(({ slug, label, description, phase, icon: Icon }) => <View key={slug} style={styles.module}><View style={styles.moduleTop}><Icon size={19} color={colors.gold} /><View style={styles.phase}><Text style={styles.phaseText}>PHASE {phase}</Text></View></View><Text style={styles.moduleTitle}>{label}</Text><Text style={styles.moduleDescription}>{description}</Text><View style={styles.ready}><Text style={styles.readyText}>ROUTE READY</Text><ArrowUpRight size={13} color={colors.textMuted} /></View></View>)}</View></ScrollView>;
}

const styles = StyleSheet.create({
  page: { flexGrow: 1, padding: spacing.xxl, paddingBottom: 64 }, heading: { maxWidth: 700 }, title: { color: colors.text, fontFamily: fontFamilies.displaySemiBold, fontSize: 34, lineHeight: 38 }, subtitle: { maxWidth: 590, marginTop: spacing.sm, color: colors.textSecondary, fontFamily: fontFamilies.sans, fontSize: 13, lineHeight: 20 },
  status: { maxWidth: 800, marginTop: spacing.xxxl, flexDirection: "row", alignItems: "center", gap: spacing.md, padding: spacing.lg, borderRadius: radii.largeCard, backgroundColor: "rgba(61,255,138,.05)" }, statusIcon: { width: 44, height: 44, borderRadius: radii.card, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(61,255,138,.08)" }, statusCopy: { flex: 1 }, statusTitle: { color: colors.text, fontFamily: fontFamilies.sansSemiBold, fontSize: 13 }, statusText: { marginTop: 4, color: colors.textSecondary, fontFamily: fontFamilies.sans, fontSize: 11, lineHeight: 17 },
  sectionTitle: { marginTop: 44, marginBottom: spacing.lg, color: colors.text, fontFamily: fontFamilies.sansSemiBold, fontSize: 15 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md }, module: { width: 250, minHeight: 164, padding: spacing.lg, borderRadius: radii.largeCard, backgroundColor: colors.surfaceRaised }, moduleTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, phase: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: radii.xs, backgroundColor: "rgba(224,184,74,.08)" }, phaseText: { color: colors.gold, fontFamily: fontFamilies.sansBold, fontSize: 8, letterSpacing: .7 }, moduleTitle: { marginTop: spacing.lg, color: colors.text, fontFamily: fontFamilies.sansSemiBold, fontSize: 13 }, moduleDescription: { marginTop: 5, color: colors.textMuted, fontFamily: fontFamilies.sans, fontSize: 10.5, lineHeight: 16 }, ready: { marginTop: "auto", paddingTop: spacing.md, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, readyText: { color: colors.textMuted, fontFamily: fontFamilies.sansBold, fontSize: 8, letterSpacing: .8 },
});
